### ISSUE TITLE
Client ID and URL

### ISSUE THREAD

**Issue by Tereseus** [Kycoo17/Jammming#1]
There is an issue obtaining the access token for your repo, I noticed in your code as well how it will not redirect to the correct location. I am not sure how you were able to setup the saving of the playlist with this issue. Did you perhaps make an accidental edit?

See below for the issue and for a solution:

![clinetid](https://user-images.githubusercontent.com/19315896/45934657-27836e00-bf6f-11e8-923a-bbd303432ac7.png)

getAccessToken() {
    if (accessToken) {
      return accessToken;
    }

    const accessTokenMatch = window.location.href.match(/access_token=([^&]*)/);
    const expiresInMatch = window.location.href.match(/expires_in=([^&]*)/);
    if (accessTokenMatch && expiresInMatch) {
      accessToken = accessTokenMatch[1];
      const expiresIn = Number(expiresInMatch[1]);
      window.setTimeout(() => accessToken = '', expiresIn * 1000);
      window.history.pushState('Access Token', null, '/'); // This clears the parameters, allowing us to grab a new access token when it expires.
      return accessToken;
    } else {
      const accessUrl = `https://accounts.spotify.com/authorize?client_id=${clientId}&response_type=token&scope=playlist-modify-public&redirect_uri=${redirectUri}`;
      window.location = accessUrl;
    }
  },

**Comment by KirtashW17** [comment]
I think the only issue was the client id which i removed intentionally. I re-inserted it , commited and now works,  the code given by you of getAccesToken results in an infinite loop. now works properly.
I will update the surge webpage in a few moments.
