### ISSUE TITLE
Summary - Unable to continue

### ISSUE THREAD

**Issue by Tereseus** [Kycoo17/Jammming#3]
The inability to obtain the correct accesstoken/url is preventing me from testing the functionality of the rest of your app. From reading your code I have seen that you have done many things correctly but there are small issues here and there. Once you fix the access issue ping me here and I will regrade your project.

**Comment by KirtashW17** [comment]
All solved, sry for taking a long time.

**Comment by KirtashW17** [comment]
@Tzuridis

**Comment by KirtashW17** [comment]
@Tzuridis Still waiting the review.

**Comment by Tereseus** [comment]
Kycoo17 your project is no longer in my que for review so I can not mark it as complete. Can you resubmit your project for review?

**Comment by KirtashW17** [comment]
@Tzuridis I clicked to resubmit but it says my project was reviwed, and i didn't received any credential score of the completation of the course, i'm a little bit disappointed.

**Comment by Tereseus** [comment]
Ok let me take a look I will try to get it back into my queue

**Comment by Tereseus** [comment]
Hey Kycoo17 so I was able to get your project back in my queue from sjlagase. After running your code every aspect of your project is perfect as it works correctly and your code is clean and concise. The only thing I recommend is using more notes/comments, that will especially help you when you work on large projects or have contributors who help you on large projects. I also see your readme is in Spanish first, my recommendation as someone who is also not a native English speaker is to put the English sections first because it is the lingua franca. Great job on everything, keep up the good work and you can close these issues now.
