### ISSUE TITLE
Feature Request - Exceeds Expectations

### ISSUE THREAD

**Issue by sjlagasse** [Kycoo17/Jammming#4]
Your feature request is in Spanish. Is there any way that you can provide an English version?

**Comment by KirtashW17** [comment]
I asked to Z-Moderator if i can uploadm the Design Document in spanish becouase i haven't got a fluent english and he sayd yes, i have to re-write all the document????

**Comment by KirtashW17** [comment]
@sjlagasse

**Comment by sjlagasse** [comment]
@Kycoo17 
Turns out Google docs has a translate document feature if you go to "tools -> translate document".

You did an awesome job on your feature request. You pointed out so many features that you could add to the project even though you only had to do one. Great job adding a background for each one to give more detail about the feature. Your best work is in the technical design. Your review really shined because of the amount of code you added to each area. You gave a detailed overview on how to implement the code which is great. I love how you added images to provide even more detail. Lastly, nice job covering your edge cases in your caveats. All in all, you went above and beyond in your project and you did an excellent job. Keep up the great work.

Google translation:

Hiciste un trabajo increíble en tu solicitud de funciones. Señaló tantas características que podría agregar al proyecto, aunque solo tenía que hacer una. Excelente trabajo al agregar un fondo para cada uno para dar más detalles sobre la función. Tu mejor trabajo está en el diseño técnico. Tu opinión realmente brilló debido a la cantidad de código que agregaste a cada área. Usted dio una descripción detallada sobre cómo implementar el código que es genial. Me encanta cómo agregó imágenes para proporcionar aún más detalles. Por último, buen trabajo cubriendo tus casos extremos en tus advertencias. En general, fue más allá en su proyecto e hizo un excelente trabajo. Mantener el buen trabajo.

**Comment by KirtashW17** [comment]
=) Thanks you very much ! I really enjoyed the course!
